# This Github action will create a Github release for updated helm-charts
name: charts-release-action

# Triggers the action on push/merge to the main branch
on:
  push:
    branches:
      - main

jobs:
  # This job will perform a helm release of all the karavi charts that have been updated
  release:
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"    
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
          id: install
  
      - name: Add Helm repos
        working-directory: ./charts/container-storage-modules/
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add tanzu https://vmware-tanzu.github.io/helm-charts
          helm repo add nginx-stable https://helm.nginx.com/stable
          
      - name: Build csm-app-mobility dependencies
        working-directory: ./charts/csm-application-mobility/
        run: helm dependency build
      
      - name: Build csm-app-mobility dependencies
        working-directory: ./charts/csm-application-mobility/
        run: helm dependency build

      - name: Build karavi-observability dependencies
        working-directory: ./charts/karavi-observability/
        run: helm dependency build

      - name: Build container-storage-modules dependencies
        working-directory: ./charts/container-storage-modules/
        run: helm dependency build

     # Run the helm chart release command
      - name: Run karavi chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:  
          charts_dir: charts
